### ISSUE TITLE
Error: No Auth Provider found for name "oidc"

### ISSUE THREAD

**Issue by mmack** [eldadru/ksniff#21]
I get this error:

```
(⎈ stage:kube-system)➜  kube-system git:(master) k sniff coredns-77594c5b55-ck7kb -v
INFO[0000] running in verbose mode                      
Error: No Auth Provider found for name "oidc"
```

```
(⎈ stage:kube-system)➜  kube-system git:(master) k version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

Any idea was happening here?

**Comment by eldadru** [comment]
First, thank you very much for using and reporting issues in ksniff!

It seems that in order to support OIDC and GCP auth providers I had to import those directly,
I merged the fix and released a new version that should fix that: https://github.com/eldadru/ksniff/releases/download/v1.2.2/ksniff.zip

Please download the new release and replace your local binary of ksniff with the one from the new release.

Please update if that resolves your issue.

**Comment by mmack** [comment]
I'm not using gcp. Its a bare metal cluster on premise.

**Comment by eldadru** [comment]
I'v added the "oidc" auth provider as well, which seems to be the issue in your case - did you try the new version and it failed?

**Comment by eldadru** [comment]
@mmack closing the issue for now, please reopen if the fix didn't resolved it for you.
